#!/bin/bash

#SBATCH --gres=gpu:0
#SBATCH --job-name=MoveToProject
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=04:00:00
#SBATCH --mem=32000M
#SBATCH --output=jobs/slurm_output/move_to_project_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/equiv-neural-rendering/

# cp -r  org_data/ /project/gpuuva022/shared/equiv-neural-rendering/org_data/
cp -r  data_prep/dataset/ /project/gpuuva022/shared/equiv-neural-rendering/objects/ 
cp -r  data_prep/output/ /project/gpuuva022/shared/equiv-neural-rendering/data/ 