#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=create_rtdata
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=06:00:00
#SBATCH --mem=32000M
#SBATCH --output=jobs/slurm_output/create_rtdata%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/equiv-neural-rendering/
source activate nr

srun python -u src/scripts/create_batch.py  -- --n_images 50